method: bayes
metric: 
  name: S Test
  goal: maximize
name: Jacobian Frac Sweep - Metric Test Acc (test)
parameters: 
  nonbase_loss_frac: 
    distribution: log_uniform
    min: -3
    max: -1
early_terminate: 
  type: hyperband
  min_iter: 5