program: Lent/distill_sweep.py 
method: grid
metric: 
  name: S Test
  goal: maximize
name: Jacobian Frac Sweep - Metric Test Acc (test)
parameters: 
  nonbase_loss_frac: 
#     distribution: log_uniform_values
#     min: 0.01
#     max: 0.75
    values: [0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.25, 0.2, 0.15, 0.1, 0.07, 0.03, 0.01]
# early_terminate: 
#   type: hyperband
#   min_iter: 5