program: Lent/distill_sweep.py
method: grid
metric: 
  name: S Loss
  goal: minimize
name: WRN arch sweep
parameters: 
  wrn_config.width_factor:
    values: [1, 2, 3, 5, 10]
  wrn_config.blocks_per_stage:
    values: [1, 2, 3, 5, 10]
# early_terminate: 
#   type: hyperband
#   min_iter: 5