- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 0
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 0
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 0
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 0
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 0
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 0
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 1
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 1
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 1
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 1
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 1
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 1
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 2
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 2
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 2
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 2
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 2
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 2
  teacher_num: 1
