model_type: RN18AP
dataset_type: DOMINOES
config_type: FRAC
sampling_method: "SGLD"
criterion: "MSE" # "MSE", "CE" or "KL"
sigma: 0.25
dataloader:
  num_train_samples: 1000 # Also gives batch size
optimization:
  lr: 0.0005
  num_samples: 10000 # Default could also be length of dataset
sgnht_kwargs: 
  diffusion_factor: 0.01
  bounding_box_size: 0.5
sgld_kwargs:
  elasticity: 1.0
  temperature: "adaptive"

num_draws: 1000
num_chains: 10
num_burnin_steps: 0 
num_steps_bw_draws: 5 
cores: 1
seed:
  # Default: None. Can be an int or a list of ints.
  # Example: 1234 or [1234, 5678]
pbar: true  # Progress bar
verbose: true
return_weights: true