- experiment_num: 0
  loss_num: 0
  student_num: 0
  teacher_num: 0
- experiment_num: 0
  loss_num: 1
  student_num: 0
  teacher_num: 0
- experiment_num: 1
  loss_num: 0
  student_num: 0
  teacher_num: 0
- experiment_num: 1
  loss_num: 1
  student_num: 0
  teacher_num: 0
- experiment_num: 2
  loss_num: 0
  student_num: 0
  teacher_num: 0
- experiment_num: 2
  loss_num: 1
  student_num: 0
  teacher_num: 0
